### PR TITLE
install: use a cpio passthrough function for root

### PR DESCRIPTION
**Pull request by rminnich**
Just doing a dumb raw dd of partitions is too dangerous.
This way we can figure out if the cpio is valid and not
copy the whole partition if the cpio is smaller (and it
is by a lot).

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by rminnich** [comment]
untested.

**Comment by rminnich** [comment]
the install works, can't test, my celes is still pretty busted.

**Comment by TrevorFarrelly** [comment]
For me, after install, every symlink on startup fails, but it still boots and everything seems to be there. Not sure what would cause it.

**Comment by rminnich** [comment]
thanks for testing, we will need to try to figure out in more detail.

**Comment by rminnich** [comment]
Turns out I had forgotten to write a trailer record
This one might do it.

**Pull request merged**
