### PR TITLE
cmds/uinit: fix problem of cpio setting perms on / incorrectly

### PR DESCRIPTION
**Pull request by rminnich**
A terrible, but cautious and useful, hack.

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by thienhoang23** [comment]
I think currently, `/. ` is owned by the user (whoever built it) and not root. That's why the permission bits are wrong. 

When I prevented dynamic initramfs to build, the ` /.` was owned by root and had the correct permission bits. So, I think this bug is the result of how we unarchive the dynamic initramfs. 

I think this hack is fine, but it doesn't address the true underlying problem though.

**Comment by hagna** [comment]
I'm still seeing the same behavior, although I don't know the right behavior yet.  I get an xterm on plain X background with no running WM and on exit I get a message about installing tczs.

**Comment by thienhoang23** [comment]
Can you elaborate on what is the same behavior?  Also, does this happen after you have disabled building dynamic initramfs? And lastly, can you check if `/` is owned by root? Thanks!

**Comment by hagna** [comment]
It's just a terminal in the upper left hand corner on top of that X background.

It looks like I'm seeing the result of this line in uinit.go:381:

if err := x11("/usr/local/bin/aterm");

When I type exit X closes and I get lots of messages like this one:

Symlink /buildbin/installcommand -> /buildbin/shutdown.go failed; symlink /buildbin/installcommand /buildbin/inprocess: file exists.

How do I disable dynamic initramfs?

**Comment by thienhoang23** [comment]
OK, I see the problem now. Can you type `ls -a -l /` and see who own the `.` directory? If it's  owned by some random number that is not the `user`, It's likely that your problem has to do with #65, which is an ongoing bug in NiChrome that we still haven't fixed yet.

Also, you can disable building dynamic initramfs by setting `skip: *skiproot || true` in usb.go line 447. However, this pertains more to my original comment to Ron's PR rather than the bug you're seeing at the moment.

**Comment by hagna** [comment]
bash-4.4# ls -a -l /
drwxrwxrwx root 0 440 Apr 16 22:00 .

How are you copying output from booting chromeos?  Are you using qemu?

**Comment by thienhoang23** [comment]
I used to build NiChrome into a USB stick and boost it on a test Chromebook. So I can just write some code to pipe the output into a file and move that file into the same USB I booted with. Then I read that file on my regular machine.

If you are using qemu, for some reason, the dynamic initramfs is not unarchived and so you won't be able to see the expected result, which is 2 xterm's (1 user, 1 root, and a Chrome Browser window)

**Comment by rminnich** [comment]
OK I can confirm that a build with this commit gives me a working chromebook, with sos and wifi started. I point chrome at localhost:8000 and get the dialog for wifi.

**Comment by rminnich** [comment]
also Hagna the problem you were seeing was probably because there was no /pkg for a tmpfs mount but I'm not sure. If you ls -l / and don't see pkg that's it.

**Pull request merged**
