### PR TITLE
Add a standard Chromebook USB stick GPT

### PR DESCRIPTION
**Pull request by rminnich**
To use this, for example, assuming your usb stick is /dev/sdb:
gpt -w /dev/sdb < StandardChromeGPT

Untested.

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

### CODE REVIEW

**Comment by hagna** [comment]
This doesn't work because gpt doesn't create a protective master boot record.  Once I inserted one I was able to boot from a disk generated with gpt:

* gpt -w /dev/sdc < StandardChromeGPT
* ./usb/usb -dev=/dev/sdc
* dd if=chromeos of=/dev/sdc bs=1 count=512 # chromeos is an already working image

**Comment by rminnich** [comment]
IIUC the protective mbr is optional, so should there be an option to gpt (maybe -W?) that implies write the gpt and also write the MBR? 

Thanks, this is very helpful!

**Comment by rminnich** [comment]
I'm sort of thinking it makes sense to always write the protective MBR. I don't see any use in making it optional.

**Comment by rminnich** [comment]
oh heck I'm already writing a header. I need to see how to do the rest.

**Pull request merged**
